# General packages to install.
# Use this on new servers with mamba env update -f environment.yml
# Use pip for cf_units since mamba cf_units outdated python requirements
# NOTE: To avoid duplicate installations of extensions skip 'jupyter contrib install' See:
# https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/issues/25#issuecomment-287730514
# NOTE: Need to install latex-envs from master branch until May 2022 PR released. See:
# https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1529#issuecomment-1134250842
# NOTE: Here jupyterlab >= 4.0.0 ships with LSP utilities based on jupyterlab-lsp
# extension. Try again once all highlighting bugs worked out.
# NOTE: Using executing < 1.0.0 can cause bug where executions do not format
# correctly. Update fixes this: https://github.com/ipython/ipython/issues/13598/
# NOTE: Can install only python and fortran servers with mamba. Use LSP interface for
# bash-language-server and julia-language-server. Use native system 'clangd' for C++.
# NOTE: Try not to confuse 'mamba install python-language-server' (pyls) with
# 'mamba install python-lsp-server' (pylsp). Latter permits definition jumping.
# NOTE: Recent cf-xarray causes 'regex' import warning messages so use older version.
# See: https://cf-xarray.readthedocs.io/en/latest/whats-new.html#v0-7-8-jan-31-2023so
# NOTE: Recent xarray version has multi-index issues so use
# an older version. See: https://github.com/pydata/xarray/issues/7695
# NOTE: Should use rm -r ~/.julia/registries to fix install issues e.g. due to
# downloading macOS julia package. See: https://stackoverflow.com/a/59300263/4970632
# NOTE: After installing julia, its package manager will use the conda environment,
# so will not have clashes. See: https://stackoverflow.com/a/45947604/4970632
# NOTE: Here 'doq' required for 'vim-pydocstring' auto docstring utility.
# See: https://github.com/heavenshell/vim-pydocstring
name: base
channels:
  - conda-forge
dependencies:
  - pip
  - python
  - julia
  - bash
  - bc
  - git
  - pre-commit
  - vim
  - deno
  - tmux
  - nco
  - cdo
  - pynco
  - python-cdo
  - numpy
  - numba
  - scipy
  - sparse
  - dask
  - pandas
  - openpyxl
  - netcdf4
  - cftime
  - xarray<=2022.01.01
  - cf_xarray<0.7.8,>=0.7.5
  - pint-pandas
  - pint-xarray
  - matplotlib<3.6
  - cartopy
  - descartes
  - shapely
  - seaborn<0.13.0
  - metpy
  - ipython
  - ipykernel
  - jupyter
  - notebook
  - jupytext
  - pandoc
  - ripgrep
  - the_silver_searcher
  - universal-ctags
  - nb_conda_kernels
  - executing>=1.0.0
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jupyter-resource-usage<1.0.0
  - jupyterlab
  - jupyterlab_server
  - jupyter-lsp
  - jupyterlab-lsp
  - jupyterlab_code_formatter
  - mypy
  - flake8
  - black
  - isort
  - pytest
  - python-lsp-server
  - shellcheck
  - fortls
  - pip:
    - doq
    - bashate
    - vim-vint
    - cf_units
    - esgf-pyclient
    - pandoc-fignos
    - pandoc-eqnos
    - pandoc-tablenos
    - pandoc-secnos
    - flake8-unused-arguments
    - nbstripout
    - git+https://github.com/gruns/icecream.git  # until release increments
    - git+https://github.com/jfbercher/jupyter_latex_envs.git  # until release increments
