# General packages to install
# Use this when changing conda distributions
# NOTE: mamba cf_units has outdated python requirements so use pip
# NOTE: recent xarray version has multi-index issues: https://github.com/pydata/xarray/issues/7695
name: base
channels:
  - conda-forge
dependencies:
  - vim
  - cdo
  - nco
  - pynco
  - python-cdo
  - deno
  - numpy
  - dask
  - pandas
  - xarray
  - xarray==2022.01.01
  - scipy
  - netCDF4
  - cftime
  - cf-xarray
  - pint_xarray
  - matplotlib<3.6
  - cartopy
  - seaborn
  - metpy
  - jupytext
  - nb_conda_kernels
  - jupyter
  - jupyter-lsp
  - jupyter_nbextensions_configurator
  - jupyterlab<4.0.0
  - jupyterlab_server
  - jupyterlab-lsp
  - jupyterlab-code-formatter
  - pip:
    - cf_units
    - icecream
    - esgf-pyclient
