# General packages to install.
# Use this on new servers with mamba env update -f environment.yml
# NOTE: mamba cf_units has outdated python requirements so use pip
# NOTE: recent xarray version has multi-index issues: https://github.com/pydata/xarray/issues/7695
# NOTE: rm -r ~/.julia/registries to fix install issues: https://stackoverflow.com/a/59300263/4970632
# NOTE: after installing julia, its package manager will use the environment: https://stackoverflow.com/a/45947604/4970632
name: base
channels:
  - conda-forge
dependencies:
  - pip
  - python
  - julia
  - bash
  - python-lsp-server
  - julia-language-server
  - bash-language-server
  - flake8
  - black
  - isort
  - shellcheck
  - pytest
  - pandoc
  - vim
  - deno
  - ctags
  - tmux
  - bc
  - nco
  - cdo
  - pynco
  - python-cdo
  - numpy
  - scipy
  - dask
  - pandas
  - netcdf4
  - xarray<=2022.01.01
  - cftime
  - cf_xarray
  - pint-xarray
  - matplotlib<3.6
  - cartopy
  - seaborn
  - metpy
  - ipython
  - ipykernel
  - jupyter
  - jupytext
  - nb_conda_kernels
  - jupyter_nbextensions_configurator
  - jupyterlab<4.0.0
  - jupyterlab_server
  - jupyter-lsp
  - jupyterlab-lsp
  - jupyterlab_code_formatter
  - pip:
    - bashate
    - vim-vint
    - cf_units
    - icecream
    - esgf-pyclient
    - flake8-unused-arguments
