# General packages to install.
# Use this on new servers with mamba env update -f environment.yml
# Use pip for cf_units since mamba cf_units outdated python requirements
# NOTE: Jupyter Lab >= 4.0.0 ships with LSP utilities based on jupyterlab-lsp
# extension. Try again once all highlighting bugs worked out.
# NOTE: Executing < 1.0.0 can cause bug where excetions do not format
# correctly. Update fixes this: https://github.com/ipython/ipython/issues/13598/
# NOTE: Can install only python and fortran servers with mamba. Use LSP interface for
# bash-language-server and julia-language-server. Use native system 'clangd' for C++.
# NOTE: Try not to confuse 'mamba install python-language-server' (pyls) with
# 'mamba install python-lsp-server' (pylsp). Latter permits definition jumping.
# NOTE: Recent xarray version has multi-index issues so use
# an older version. See: https://github.com/pydata/xarray/issues/7695
# NOTE: Should use rm -r ~/.julia/registries to fix install issues e.g. due to
# downloading macOS julia package. See: https://stackoverflow.com/a/59300263/4970632
# NOTE: After installing julia, its package manager will use the conda environment,
# so will not have clashes. See: https://stackoverflow.com/a/45947604/4970632
name: base
channels:
  - conda-forge
dependencies:
  - pip
  - python
  - julia
  - bash
  - bc
  - git
  - pre-commit
  - vim
  - deno
  - ctags
  - tmux
  - nco
  - cdo
  - pynco
  - python-cdo
  - numpy
  - scipy
  - dask
  - pandas
  - netcdf4
  - xarray<=2022.01.01
  - cftime
  - cf_xarray
  - pint-xarray
  - matplotlib<3.6
  - cartopy
  - seaborn
  - metpy
  - ipython
  - ipykernel
  - jupyter
  - jupytext
  - pandoc
  - nb_conda_kernels
  - executing>=1.0.0
  - jupyter_nbextensions_configurator
  - jupyterlab<4.0.0
  - jupyterlab_server
  - jupyter-lsp
  - jupyterlab-lsp
  - jupyterlab_code_formatter
  - flake8
  - black
  - isort
  - pytest
  - python-lsp-server
  - shellcheck
  - fortls
  - pip:
    - bashate
    - vim-vint
    - cf_units
    - esgf-pyclient
    - flake8-unused-arguments
    - git+https://github.com/gruns/icecream.git  # until release increments
