#!/bin/bash
# This script is intended to carry out some basic workspace environments done to my Mac
# Try to store as many as possible here so switching to a new laptop will be more painless

# First enable the complex Karabiner remap that allows switching hyphen and underscore keys
# See this Issues page: https://github.com/tekezo/Karabiner-Elements/issues/329
# GUI instructions: Go to "Complex Modifications" in Karabiner prefs and "Add Rule"
location=~/.config/karabiner/assets/complex_modifications/exchange_hyphen_and_underscore.json
cat > $location << EOF
{
  "title": "Exchange hyphen and underscore (manually installed)",
  "rules": [
    {
      "description": "Exchange hyphen and underscore (manually installed)",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "hyphen",
            "modifiers": {
              "optional": [
                "caps_lock"
              ]
            }
          },
          "to": [
            {
              "key_code": "hyphen",
              "modifiers": [
                "left_shift"
              ]
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "hyphen",
            "modifiers": {
              "mandatory": [
                "shift"
              ],
              "optional": [
                "caps_lock"
              ]
            }
          },
          "to": [
            {
              "key_code": "hyphen"
            }
          ]
        }
      ]
    }
  ]
}
EOF
