#!/bin/bash
# shellcheck disable=2076
################################################################################
# setup
# Create symlinks from $HOME to the committed files in $HOME/dotfiles
################################################################################
# Files to be ignored
exclude=(README.md REGEXES.md .gitignore setup cleanup backup)

# Setup
root=$HOME
dotfiles=$HOME/dotfiles
cd "$dotfiles" || {
  echo "Error: dotfiles repo should be cloned into \$HOME."
  exit 1
}
read -r -a files < <(git ls-tree --name-only master | xargs)
backup=$dotfiles/backup
[ -d "$backup" ] || mkdir "$backup"

# Move existing stuff to storage, then create symlinks
for file in "${files[@]}"; do  # iterate through files
  [[ " ${exclude[*]} " =~ " $file " ]] && continue
  [ "$file" == ".gitignore.template" ] && dest=".gitignore"
  dest=$HOME/$file
  bakdest=$backup/$dest
  echo "Creating symlink to '$file' in '$HOME'..."
  if [ -L "$dest" ]; then
    echo "Removing existing symlink..."
    rm "$dest"  # remove if symlink
  elif [ -r "$dest" ]; then
    echo "Moving existing '$file' file to '$backup'..."
    if [ -e "$bakdest" ]; then
      echo "Warning: Removing existing backup..."
      rm -r "$bakdest"
    fi
    mv "$dest" "$backup/"  # copy if not
  fi
  ln -s "$dotfiles/$file" "$dest"
done

# Create variety of symlinks in home directory
opts=(~/miniconda3/lib/python3.*)
python=${opts[0]:?$HOME/miniconda3/lib/python3.*}  # raise error later error later
for pair in \
  $python:site-packages \
  $HOME/Library/Services:workflows \
  $HOME/Library/Mobile\ Documents/com~apple~CloudDocs:iCloud\ Drive \
  /Volumes/GoogleDrive/My\ Drive:Google\ Drive \
  /usr/local/texlive/2017/texmf-dist/tex/latex:tex-packages
  do
  src=${pair%:*}
  if ! [ -r "$src" ]; then
    echo "Warning: Skipping link to '$src' (path does not exist)."
    continue
  fi
  dest=$root/${pair#*:}
  echo "Creating symlink to '$src' at '$dest'..."
  if [ -L "$dest" ]; then
    echo "Removing existing symlink..."
    rm "$dest"  # remove if symlink
  elif [ -r "$dest" ]; then
    echo "Warning: Skipping link to '$src' (non-symlink exists)"
    continue
  fi
  ln -sf "$src" "$dest"
done
