#!/bin/bash
# shellcheck disable=2076
################################################################################
# setup
# Create symlinks from $HOME to the committed files in $HOME/dotfiles
################################################################################
# Files to be ignored
exclude=(README.md REGEXES.md .gitignore setup cleanup backup)

# Setup
root=$HOME
dotfiles=$HOME/dotfiles
cd "$dotfiles" || {
  echo "Error: dotfiles repo should be cloned into \$HOME."
  exit 1
}
read -r -a names < <(git ls-tree --name-only master | xargs)
backup=$dotfiles/backup
[ -d "$backup" ] || mkdir "$backup"

# Move existing stuff to storage, then create symlinks
for name in "${names[@]}"; do  # iterate through files
  [[ " ${exclude[*]} " =~ " $name " ]] && continue
  file=$dotfiles/$name
  [ "$name" == .gitignore.default ] && name=.gitgnore  # change destination name?
  dest=$HOME/$name
  bakdest=$backup/$name
  echo "Creating symlink to '${file##*/}' in '$HOME'..."
  if [ -L "$dest" ]; then
    echo "Removing existing symlink..."
    rm "$dest"  # remove if symlink
  elif [ -r "$dest" ]; then
    echo "Moving existing file '${file##*/}' to '$backup'..."
    if [ -e "$bakdest" ]; then
      echo "Warning: Removing existing backup..."
      rm -r "$bakdest"
    fi
    mv "$dest" "$backup/"  # copy if not
  fi
  ln -s "$file" "$dest"
done

# Create variety of symlinks in home directory
opts=(~/miniconda3/lib/python3.*/site-packages)
python=${opts[0]:?$HOME/miniconda3/lib/python3.*/site-packages}  # raise warning later
for pair in \
  $python:site-packages \
  /usr/local/texlive/2017/texmf-dist/tex/latex:tex-packages \
  /Volumes/GoogleDrive/My\ Drive:Google\ Drive \
  $HOME/Library/Mobile\ Documents/com~apple~CloudDocs:iCloud\ Drive \
  $HOME/Library/Services:workflows
  do
  src=${pair%:*}
  if ! [ -r "$src" ]; then
    echo "Warning: Skipping link to '$src' (path does not exist)."
    continue
  fi
  dest=$root/${pair#*:}
  echo "Creating symlink to '$src' at '$dest'..."
  if [ -L "$dest" ]; then
    echo "Removing existing symlink..."
    rm "$dest"  # remove if symlink
  elif [ -r "$dest" ]; then
    echo "Warning: Skipping link to '$src' (non-symlink exists)"
    continue
  fi
  ln -sf "$src" "$dest"
done
