#!/usr/bin/env bash
# This function does what seemingly should be doable in tmux
# with a simple command -p; for some reason had issues
pane1=$1 # source
pane2=$2 # dest
window=$(tmux display -p "#I")
tmux swap-pane -s:${window}.${pane1} -t:${window}.${pane2}
